### ISSUE TITLE
Provide a .gpx URL through GET/POST

### ISSUE THREAD

**Issue by magiraud** [vcoppe/gpx-tool#4]
Excellent tool, thank you! 

It could be nice to be able to provide a .gpx file (or even several ones) by giving some URL through a GET or a POST request.

**Comment by vcoppe** [comment]
Thanks! You can actually already do that, here an example with a random file on Github: [https://gpxstudio.github.io/?state={"urls":["https://raw.githubusercontent.com/gps-touring/sample-gpx/master/RoscoffCoastal/parcours-morlaix-plougasnou.gpx"]}](https://gpxstudio.github.io/?state={"urls":["https://raw.githubusercontent.com/gps-touring/sample-gpx/master/RoscoffCoastal/parcours-morlaix-plougasnou.gpx"]}). You can put any number of files in the URL list (with commas in between).
However, the website must be allowed to request those files otherwise the requests will be blocked by the CORS policy.
Another option is to use the Google Drive plugin to easily open and save multiple files.
